### ISSUE TITLE
Api Key exposed

### ISSUE THREAD

**Issue by TuningYourCode** [bastianschott/ezMail#10]
Not sure if you wanted to public expose your google api key:

https://github.com/bastianschott/ezMail/blob/master/src/environments/environment.ts

I was browsing https://shhgit.darkport.co.uk/ and it listed your commited file.

**Comment by bastianschott** [comment]
Hey @TuningYourCode,

I'm aware of this issue, but this app is for a class in a course I'm visiting. For an easier collaboration, I've included the file. This project will only generate pseudo data on firebase, so there will be no big security issue :)

Thank you for the report!
Cheers
Bastian
