### ISSUE TITLE
sidenav is not shown between 936 und 960 px

### ISSUE THREAD

**Issue by strozynskib** [bastianschott/ezMail#11]
Beim skallieren des Fensters in der Breite zeigt sich dass die Sidenav Menüleiste zwischen 936px und 960px nicht zu sehen ist.
![2019-10-21 19_06_30-EzMail](https://user-images.githubusercontent.com/53255146/67226724-eee5ea80-f435-11e9-858b-53826f16da19.png)

**Comment by bastianschott** [comment]
Funktioniert bei mir
Am besten mal pullen und erneut versuchen ;)

**Comment by strozynskib** [comment]
works as designed. --->Tablet mode
