### ISSUE TITLE
Visibility of menu items if not logged in

### ISSUE THREAD

**Issue by bastianschott** [bastianschott/ezMail#12]
Die Menüelemente sollten alle ausgeblendet werden, falls man nicht eingeloggt ist. Auch müssen die Routen geschützt werden, damit man nicht unbefugt auf z.B. das Dashboard kommt.

**Comment by bastianschott** [comment]
Ist inzwischen implementiert.

Ein Problem gibt es jedoch: Wenn man eingeloggt ist und auf Mail-Einstellungen klickt, kommt man auf den Login

**Comment by strozynskib** [comment]
Läuft alles nun.
