### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by bastianschott** [bastianschott/ezMail#13]
Der offizielle Styleguide von Angular sagt aus, dass man auch in den Dateinamen mit kebab-case und nciht mit camelCase arbeiten soll:
https://angular.io/guide/styleguide#separate-file-names-with-dots-and-dashes

Alle bisherigen Dateien refaktorieren?

**Comment by bastianschott** [comment]
Zusätzlich können wir Codelyzer benutzen, um sich an den Style Guide zu halten:
https://angular.io/guide/styleguide#codelyzer

**Comment by strozynskib** [comment]
wir haben kebab-case schon.....
